name: diamond_selection
description: "A new Flutter project."


publish_to: 'none'













version: 1.0.0+1

environment:
  sdk: ^3.6.0







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  go_router: ^14.8.1
  get_it: ^8.0.3
  dartz: ^0.10.1
  equatable: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0





flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter_28pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_28pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_28pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter_28pt-Thin.ttf
          weight: 100
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
